[package]
name = "minimal_mult"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "bench_mont_mult_barebones"
harness = false

[[bench]]
name = "bench_sumcheck_bind"
harness = false

[profile.release-with-debug]
inherits = "release"
debug = true
